version: "2.1"

services:
  landings:
    container_name: random-quotes
    image: random-quotes
    restart: always
    build: .
    environment:
      NODE_ENV: production
    ports:
      - "8080:8080"
    logging:
      options:
        max-size: 50m